id: 8156a9b564fb4f7fa0152c942bd71016
initial_creation_type: ocr
source_metadata:
  volumes:
    cdaad417267b4290b83c074910e6b399:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
